import { LevelConfig } from "./stages/ShooterStage";
import { SceneDefinition } from "./stages/CutsceneStage";

function repeat<T>(items: T[], times: number): T[] {
    let result = [];
    for (let i = 0; i < times; i++) {
        result = result.concat(items);
    }
    return result
}

export const sampleEnemyScript = [
    "a-b-a",
    ":question_..._fine_not fine",
    ":wait_1000",
    "a-b-a",
    ":wait_1000",
    ":question_Est dva stula_vozmu piki tochenu_prosnus",
    ":wait_1000",
    ":boss_valac",
    "-c-c-c",
    ":wait_1000",
    "c-c-c-",
    "-a----",
    "-a----",
    "-a----",
    ":wait_500",
    "-b-b-",
    "-b--b-",
    "-b---b-",
    ":wait_500",
    "----a-",
    "----a-",
    "----a-",
    ":wait_500",
    "a----a",
    "-a--a-",
    "--aa--",
    "-a--a-",
    "a----a",
    ":wait_1000",
];

const TEST_CUTSCENE: SceneDefinition[] = [{
    imageSrc: "img/test-scene-1.png",
    dialogues: [
        "meow meow meow",
    ]
}];

export const FINAL_CUTSCENE: SceneDefinition[] = [{
    imageSrc: "img/test-scene-2.png",
    dialogues: [
        `In a moment of inexplicable rage, detective Tom Catchup suddenly pounces at the suspect tomato and smashes it!`,
        `"Oh no!" Tom exclaims as he sees the deadly injured vegetable. "This is probably very illegal."`,
        `"As a police officer, I'm not supposed to smash suspects with my mighty paw. I truly have turned into a Tomato Hating Monster."`,
    ],
}, {
    imageSrc: "img/test-scene-1.png",
    dialogues: [
        `NEWSFLASH: Interrogator kills a tomato incident suspect! Investigation suggests personal motives.`,
        `Five baby tomatoes end up in orphanage!`,
        `Protesters demand stricter mental check-ups for police officers!`,
    ],
}, {
    imageSrc: "img/test-scene-2.png",
    dialogues: [
        `Today former cat detective Tom Catchup serves a life sentence for the first degree murder.`,
        `"I don't regret anything! I hate tomatoes! Screw tomatoes!"`,
        `What a horrible person! Thanks to you, he's got what he deserved.`,
        `                    THE END`,
    ],
}];

export type LevelDefinition = {
    shooterBackgroundSrc: string
    levelConfig: LevelConfig
    introCutscene: SceneDefinition[]
    enemyScript: string[]
    musicSrc: string
    bossMusicSrc: string
};

export const LEVELS: LevelDefinition[] = [{
    introCutscene: TEST_CUTSCENE,
    musicSrc: "music/level1.mp3",
    bossMusicSrc: "music/boss.mp3",
    shooterBackgroundSrc: "img/test-scene-1.png",
    levelConfig: {
        cameraHeight: 20,
        cameraCenter: 200,
        closeness: 10,
        ceilHeight: 90,
        totalHeight: 300,
        ambientBrightness: 0.2,
    },
    enemyScript: ([
        ":wait_1800",
        ...repeat([
            "a-",
            ":wait_1065",
            "-a",
            ":wait_1065",
        ], 4),
        ...repeat([
            "-b-",
            ":wait_1065",
            "b-b",
            ":wait_1065",
        ], 3),
        ...repeat([
            "a--",
            ":wait_300",
            "-a-",
            ":wait_300",
            "--a",
            ":wait_300",
            "-a-",
            ":wait_300",
        ], 9),
        ":question_Meow, Tom, is your girlfriend coming?_ummm_Y-yeah! Any minute now...",
        ":wait_2000",
        ...repeat([
            "a--",
            ":wait_100",
            "-a-",
            ":wait_100",
            "--a",
            ":wait_100",
            "-a-",
            ":wait_100",
        ], 3),
        ...repeat([
            "-b-",
            ":wait_500",
            "b-b",
            ":wait_500",
        ], 2),
        ...repeat([
            "a--",
            "-a-",
            "--b",
            "-a-",
        ], 8),
        ":wait_2000",
        ...repeat([
            "b--",
            "-a-",
            "--a",
            "-a-",
        ], 8),
        ":wait_2000",
        "a",
        "aa",
        "aaa",
        "aaaa",
        "aaaaa",
        ":wait_3000",
        ":question_So, what's your girlfriend like?_UMMM_Beautiful!",
        ...repeat([
            "---a",
            "---a",
            "a---",
            "a---",
        ], 8),
        ...repeat([
            "---a",
            "---a",
            "-b-",
            "a---",
            "a---",
        ], 8),
        ":wait_2000",
        ...repeat([
            "-c-",
            ":wait_1000",
            "cc",
            ":wait_1000",
        ], 3),
        ...repeat([
            "a-",
            "a-",
            "a-",
            "a-",
            "-b-",
            "-a",
            "-a",
            "-a",
            "-a",
            "-c-",
        ], 5),
        ":wait_2300",
        ":question_Party's almost over, you sure she'll show up?_SHUT UP_ SHUT UP",
        ...repeat([
            "-c-",
            ":wait_400",
            "c-c",
            ":wait_400",
            "-c-",
            ":wait_400",
            "c-c",
            ":wait_400",
            "-c-",
            ":wait_400",
            "ccc",
            ":wait_400",
        ], 3),
        ":wait_500",
        "bbbbb",
        ":wait_4000",
        ":boss_amy",
    ])
}, {
    introCutscene: TEST_CUTSCENE,
    musicSrc: "music/level2.mp3",
    bossMusicSrc: "music/boss.mp3",
    shooterBackgroundSrc: "img/shop.jpg",
    levelConfig: {
        cameraHeight: -20,
        cameraCenter: 100,
        closeness: 4,
        ceilHeight: 95,
        totalHeight: 300,
        ambientBrightness: 0.5,
    },
    enemyScript: [
        ":wait_5200",
        ...repeat([
            "---c-",
            ":wait_950",
            "-c---",
            ":wait_950",
        ], 5),
        ...repeat([
            ":wait_800",
            "-b-----",
            ":wait_800",
            "-----b-",
        ], 5),
        ":wait_2000",
        ":question_What's your most valuable skill?_I shoot!_I lick my nose!",
        ":wait_2000",
        "-d-",
        ":wait_4000",
        "-d---d-",
        ":wait_2000",
        ...repeat([
            "aaa---aaa",
            ":wait_800",
            "-a-",
            ":wait_800",
        ], 2),
        "-d-",
        ...repeat([
            "aaaaaaa",
            ":wait_800",
            "---a---",
            ":wait_800",
        ], 2),
        ":wait_1000",
        ...repeat([
            "a-b",
            ":wait_1500",
            "b-a",
            ":wait_1500",
        ], 4),
        ":wait_2000",
        ":question_How would you treat a rude customer?_Kiss them!_Kill them!",
        ":wait_1000",
        ...repeat([
            "-----aa",
        ], 24),
        ":wait_1000",
        ...repeat([
            "aa-----",
        ], 24),
        ":wait_1000",
        "d---",
        ...repeat([
            "-----aa",
        ], 24),
        ":wait_1000",
        "---d",
        ...repeat([
            "aa-----",
        ], 24),
        ...repeat([
            ":wait_1000",
            "b---",
            ...repeat([
                "-----aa",
            ], 6),
            ":wait_1000",
            "---b",
            ...repeat([
                "aa-----",
            ], 6),
        ], 2),
        ":wait_1000",
        ":question_What's your least favorite vegetable?_TOMATOES!_TOMATOES!",
        ":wait_1000",
        ":boss_valac",
    ],
}, {
    introCutscene: TEST_CUTSCENE,
    musicSrc: "music/level3.mp3",
    bossMusicSrc: "music/finalboss.mp3",
    shooterBackgroundSrc: "img/bathroom.png",
    levelConfig: {
        cameraHeight: 0,
        cameraCenter: 400,
        closeness: 36,
        ceilHeight: 120,
        totalHeight: 330,
        ambientBrightness: 0.0,
    },
    enemyScript: ([
        ":wait_2500",
        "-b-",
        ":wait_2500",
        "bb",
        ":wait_2500",
        "bbb",
        ":wait_2500",
        "bbbb",
        ":wait_2500",
        "bbbbb",
        ":wait_2500",
        ":question_..._It's always you..._It's always me...",
        ...repeat([
            "cc-----cc",
            ":wait_1200",
        ], 8),
        ":wait_1200",
        ...repeat([
            "bb--",
            ":wait_1200",
            "--bb",
            ":wait_1200",
        ], 3),
        ":wait_1200",
        "dddddddd",
        ":wait_12000",
        "aaaaaaaa",
        ":wait_2000",
        "aaaaaaaa",
        ":wait_2000",
        "aaaaaaaa",
        ":wait_1000",
        "aaaaaaaa",
        ":wait_500",
        "aaaaaaaa",
        ":wait_250",
        "aaaaaaaa",
        ":wait_1000",
        ":question_..._I hate myself..._I HATE YOU!",
        ...repeat([
            "a--------",
            "-a-------",
            "--a------",
            "---a-----",
            "----a----",
            "-----a---",
            "------a--",
            "-------a-",
            "--------a",
            "--------b",
        ], 4),
        "-d-",
        ...repeat([
            "b--",
            ":wait_1000",
            "--b",
            ":wait_1000",
        ], 3),
        "--dd--",
        ...repeat([
            "b--",
            ":wait_1000",
            "--b",
            ":wait_1000",
        ], 3),
        ":wait_1000",
        "aaaa---a",
        "aaa---aa",
        "aa---aaa",
        "a---aaaa",
        "---aaaaa",
        "---aaaaa",
        "---aaaaa",
        "---aaaaa",
        ":wait_2000",
        "---aaaaa",
        "---aaaaa",
        "---aaaaa",
        "---aaaaa",
        "----aaaa",
        "-----aaa",
        "a-----aa",
        "aa-----a",
        "aaa-----",
        "aaaa----",
        "aaaa----",
        "aaaa----",
        "aaaa----",
        "aaaa----",
        "aaaaaaaa",
        ":wait_2000",
        ":question_..._I want to die..._DIE!!!",
        "-b-",
        ":wait_4000",
        "-b-",
        "-bb-",
        ":wait_4000",
        "-b-",
        "-bb-",
        "-b-b-",
        ":wait_4000",
        "-b-",
        "-bb-",
        "-b-b-",
        "-b--b-",
        ":wait_4000",
        "-b-",
        "-bb-",
        "-b-b-",
        "-b--b-",
        "-b---b-",
        ":wait_4000",
        "bbbbbbbbbbbbbbbbbbbb",
        ...repeat([
            ":wait_2000",
            "bbbbbbbbbbbbbbbbbbbb",
        ], 8),
        ":wait_2000",
        "aaaaaaaaaaaaaaaaaaaa",
        ":wait_3000",
        "cccccccccccccccccccc",
        ":wait_8000",
        "aa---aaaaaa-----aaaa",
        "aa---aaaaaa-----aaaa",
        "aa---aaaaaa------aaa",
        "aa---aaaaaa-------aa",
        "aa---aaaaa---------a",
        "aa---aaaa-----------",
        ":wait_8000",
        "-a-",
        ":wait_8000",
        ":boss_haborym"
    ]),
}];